project:
  type: website

website:
  
  title: "Intelligent Systems Lab"
  favicon: favicon.ico
  site-url: https://isl-hosei.github.io/
  description: "Intelligent Systems Lab at Hosei University"
  open-graph: true
  navbar:
    logo: images/logo.ico
    left:
      - href: index.qmd
        text: "<span style='font-size:16px;'>Home</span><br><span style='font-size:12px;'>ホーム</span>"
      - people.qmd
      - research.qmd
      - href: news.qmd
        text: News
      - join.qmd
      - contact.qmd
    right:
      - text: ゼミ
        menu:
          - text: ダウンロード
            href: seminar/download.qmd
          - text: 学会日程
            href: seminar/conference.qmd

      - icon: github
        href: https://github.com/isl-hosei
    # - icon: github
      #   href: https://github.com/
      # - icon: twitter
      #   href: https://twitter.com
  page-footer: 
    center: "Copyright 2025, Intelligent Systems Lab, Hosei University"
    right: |
      [法政大学](https://www.hosei.ac.jp/)
      [経営システム工学科](https://ise-hp.ws.hosei.ac.jp/)
      [知能システム研究室](https://isl-hosei.github.io/)
format:
  html:
    theme: Flatly
    css: styles.css



