project:
  type: website

website:
  
  title: "Intelligent Systems Lab"
  favicon: favicon.ico
  site-url: https://isl-hosei.github.io/
  description: "Intelligent Systems Lab at Hosei University"
  open-graph: true
  navbar:
    logo: images/logo.ico
    left:
      - href: index.qmd
        text: "<span style='font-size:16px;'>Home</span><br><span style='font-size:12px; opacity:0.8;'>ホーム</span>"
      
      - href: people.qmd
        text: "<span style='font-size:16px;'>People</span><br><span style='font-size:12px; opacity:0.8;'>メンバー</span>"

      - href: research.qmd
        text: "<span style='font-size:16px;'>Research</span><br><span style='font-size:12px; opacity:0.8;'>研究内容</span>"

      - href: news.qmd
        text: "<span style='font-size:16px;'>News</span><br><span style='font-size:12px; opacity:0.8;'>ニュース</span>"
      - href: join.qmd
        text: "<span style='font-size:16px;'>Join Us</span><br><span style='font-size:12px; opacity:0.8;'>募集</span>"
      - href: contact.qmd
        text: "<span style='font-size:16px;'>Contact</span><br><span style='font-size:12px; opacity:0.8;'>アクセス</span>"
    right:
      - text: "Seminar"
        href: seminar/intro.qmd

      - icon: github
        href: https://github.com/isl-hosei
    # - icon: github
      #   href: https://github.com/
      # - icon: twitter
      #   href: https://twitter.com
  
  sidebar:
    - title: Seminar
      contents:
        - seminar/intro.qmd
        - seminar/lab-info.qmd
        - seminar/conference.qmd
        - seminar/thesis.qmd
        - seminar/research-tools.qmd
        - text: "---"
        - section: "卒業研究"
          contents:
            - seminar/b4/thesis-check-sheet.qmd
            - seminar/b4/slide-check-sheet.qmd
        - text: "---"
        - section: "資源"
          contents:
            - seminar/resources/e-book.qmd
            - seminar/resources/Kinoden.qmd

  
  page-footer: 
    center: "Copyright 2025, Intelligent Systems Lab, Hosei University"
    right: |
      [法政大学](https://www.hosei.ac.jp/)
      [経営システム工学科](https://ise-hp.ws.hosei.ac.jp/)
      [知能システム研究室](https://isl-hosei.github.io/)
format:
  html:
    theme: Flatly
    css: styles.css



